volume:
  defaults: #define the defaults for all Persistent Volumes
      storage: 5Gi
      persistentVolumeReclaimPolicy: Recycle

volumes:
    pv0001:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0002:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0003:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0004:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0005:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0006:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0007:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0008:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0009:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv0010:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"