---
- hosts: "{{ openshift_node }}"
  gather_facts: False

  vars:
    number_of_users: 1
    first_user_offset: 1

  tasks:

    - name: Install python dependency
      pip:
        name: passlib

    - name: Create users
      htpasswd:
          path: /etc/origin/master/htpasswd
          name: "user{{ item }}"
          password: "pwd{{ item }}"
      with_sequence: start={{ first_user_offset }} count={{ number_of_users }} format=%d

    - name: Restart master
      include_role:
          name: restart_master

    - name: Create project for each user
      shell: |
        oc login -u admin -p admin
        oc delete project user{{ item }} --ignore-not-found=true
        sleep 15
        oc login -u user{{ item }} -p pwd{{ item }}
        oc new-project user{{ item }}
        oc login -u admin -p admin
        oc adm policy add-cluster-role-to-user edit system:serviceaccount:infra:jenkins -n user{{ item }}
        sleep 5
      with_sequence: start={{ first_user_offset }} count={{ number_of_users }} format=%d

            