---
- hosts: "{{ openshift_node }}"
  gather_facts: False
  tasks:
    - name: Shutdown Openshift cluster - oc cluster down
      import_role:
        name: cluster
        tasks_from: cluster_down.yml
      tags: down

    - name: Start Openshift cluster
      import_role:
        name: cluster
        tasks_from: cluster_start.yml
      tags: start

    - name: Create Openshift cluster - oc cluster up
      import_role:
        name: cluster
        tasks_from: main.yml
      tags: up

    - name: Openshift cluster status
      import_role:
        name: cluster
        tasks_from: cluster_status.yml
      tags: status

    - name: Clean Openshift configs
      import_role:
        name: cluster
        tasks_from: cluster_clean.yml
      tags: clean
