---
- hosts: "{{ openshift_node | default('masters') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  roles:
    - { role: 'enable_cluster_admin', tags: 'enable_cluster_admin', when: target_platform == 'cloud' }
    - { role: 'create_projects',      tags: 'create_projects'}
    - { role: 'persistence',          tags: 'persistence',          when: target_platform == 'cloud' }
    - { role: 'install_nexus',        tags: 'nexus'}
    - { role: 'install_jenkins',      tags: 'jenkins'}
    - { role: 'install_jaeger',       tags: 'jaeger'}
    - { role: 'install_istio',        tags: 'istio',                when: service_mesh | default('false') | bool == true }
    - { role: 'identity_provider',    tags: 'identity_provider'}
    

# Unfortunately this can't be a separate role, because the path where the various playbooks are looked up get's messed-up
- include: '../openshift-ansible/playbooks/byo/openshift-cluster/service-catalog.yml'
  vars:
    ansible_service_broker_registry_whitelist: [".*-apb$"]
    ansible_service_broker_install: true
    ansible_service_broker_registry_tag: v3.7
    ansible_service_broker_image_tag: v3.7
  tags:
    - install_asb
  when:
    experimental_features | default('disable') == 'enable'