---
- hosts: "{{ openshift_node | default('masters') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  roles:
    - { role: 'persistence',          tags: 'persistence'}          # When Minishift or oc cluster up is NOT used
    - { role: 'identity_provider',    tags: 'identity_provider'}    # Use HTPasswdPasswordIdentityProvider as Identity Provider -> more secure
    - { role: 'enable_cluster_admin', tags: 'enable_cluster_admin'} # When oc cluster up is used
    - { role: 'install_oc',           tags: 'install_oc'}           # Install oc client when cluster role is not used
    - { role: 'create_projects',      tags: 'create_projects'}
    - { role: 'install_nexus',        tags: 'nexus'}
    - { role: 'install_jenkins',      tags: 'jenkins'}
    - { role: 'install_jaeger',       tags: 'jaeger'}
    - { role: 'install_istio',        tags: 'istio'}

  tasks:
    # Launcher Role
    - name: Install launcher
      import_role:
        name: launcher
        tasks_from: install.yml
      tags: install-launcher

    - name: Uninstall launcher
      import_role:
        name: launcher
        tasks_from: uninstall.yml
      tags:
        - uninstall-launcher

    - name: Patch launcher-clusters configmap
      import_role:
        name: launcher
        tasks_from: patch_configmap.yml
      tags:
        - patch-launcher


# Unfortunately this can't be a separate role, because the path where the various playbooks are looked up get's messed-up
- include: '../openshift-ansible/playbooks/byo/openshift-cluster/service-catalog.yml'
  vars:
    ansible_service_broker_registry_whitelist: [".*-apb$"]
    ansible_service_broker_install: true
    ansible_service_broker_registry_tag: v3.7
    ansible_service_broker_image_tag: v3.7
  tags:
    - install_asb
  when:
    experimental_features | default('disable') == 'enable'