---
- hosts: "{{ openshift_node }}"
  gather_facts: False
  vars:
    infra_project: infra1

  roles:
    - { role: 'enable_cluster_admin', tags: 'enable_cluster_admin'}
    - { role: 'create_projects', tags: 'create_projects'}
    - { role: 'persistence', tags: 'persistence'}
    - { role: 'install_nexus', tags: 'install_nexus'}
    - { role: 'install_jenkins', tags: 'install_jenkins'}
    - { role: 'install_jaeger', tags: 'install_jaeger'}
    - { role: 'install_asb', tags: 'install_asb'}
