- name: Create daemon.json file to define extra docker parameters such as insecure-registries
  blockinfile:
    path: /etc/docker/daemon.json
    block: |
      {
        "insecure-registries" : [ "172.30.0.0/16" ]
      }

- name: Reload systemctl daemon and restart docker service
  shell: |
    systemctl enable docker
    systemctl daemon-reload
    systemctl restart docker