---
- name: Execute Ansible service catalog playbook
  shell: |
    cd ../
    ansible-playbook -i inventory/cloud_host openshift-ansible/playbooks/byo/openshift-cluster/service-catalog.yml -e '{ "ansible_service_broker_registry_whitelist": [".*-apb$"], "ansible_service_broker_install": true, "ansible_service_broker_registry_tag": "v3.7", "ansible_service_broker_image_tag": "v3.7" }'
  delegate_to: localhost
