# Variables used to override or configure the Istio playbook

# Istio playbooks variables - see Istio Ansible README file for more info
cluster_flavour: ocp

istio:
  release_tag_name: "0.6.0"
  dest: "/home/istio"
  auth: false
  namespace: istio-system
  addon:
    - "grafana"
    - "prometheus"
    - "servicegraph"
    - "jaeger"
  samples:
    - "helloworld"