---
# Origin git hub Repo
openshift_github_user: openshift
openshift_github_name: origin
openshift_github_url: https://api.github.com/repos

# Openshift parameters
openshift_release_tag_name: "v3.7.2"

openshift_client_dest: /usr/local/bin
openshift_force_client_install: false

openshift_recreate: yes
openshift_user: admin

cluster_ip_address: 192.168.99.50
cluster_use_existing_config: true
cluster_host_config_dir: /var/lib/openshift/config
cluster_host_data_dir: /var/lib/openshift/data
cluster_host_volumes_dir: /var/lib/openshift/volumes
cluster_host_pv_dir: /var/lib/openshift/volumes/pv
cluster_service_catalog: true

openshift_up_options: '
  --version={{ openshift_release_tag_name }}
  --host-config-dir={{ cluster_host_config_dir }}
  --host-data-dir={{ cluster_host_data_dir }}
  --host-volumes-dir={{ cluster_host_volumes_dir }}
  --host-pv-dir={{ cluster_host_pv_dir }}
  --use-existing-config={{ cluster_use_existing_config }}
  --public-hostname={{ cluster_ip_address }}
  --routing-suffix={{ cluster_ip_address }}.nip.io
  --loglevel=1
  --service-catalog={{ cluster_service_catalog }}'
